[2019-05-09 21:47:22]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 361, in <module>
    run_gui(settings)
NameError: name 'settings' is not defined

[2019-05-09 21:35:37]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 358, in <module>
    ut.output = settings['utility_output']
KeyError: 'utility_output'

[2019-05-09 21:34:16]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 356, in <module>
    settings = ut.load_settings()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 396, in load_settings
    save_settings(settings)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 381, in save_settings
    json.dump(path, settings)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
AttributeError: 'dict' object has no attribute 'write'

[2019-05-09 21:33:28]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 356, in <module>
    settings = ut.load_settings()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 396, in load_settings
    save_settings(settings)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 381, in save_settings
    json.dump(settings, path)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
AttributeError: 'str' object has no attribute 'write'

[2019-05-09 21:33:02]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 356, in <module>
    settings = ut.load_settings()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 388, in load_settings
    settings = json.load(infile)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2019-05-09 21:32:21]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 356, in <module>
    settings = ut.load_settings()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 395, in load_settings
    save_settings(settings)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 380, in save_settings
    json.dump(settings, path)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
AttributeError: 'str' object has no attribute 'write'

[2019-05-09 21:11:17]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 17, in <module>
    print(test)
NameError: name 'test' is not defined

[2019-05-08 23:54:51]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 17, in <module>
    print(test)
NameError: name 'test' is not defined

[2019-05-08 23:53:11]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 17, in <module>
    print(test)
NameError: name 'test' is not defined

[2019-05-08 23:47:49]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 17, in <module>
    print(test)
NameError: name 'test' is not defined

[2019-05-08 23:47:26]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 17, in <module>
    print(test)
NameError: name 'test' is not defined

[2019-05-08 23:31:47]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 9, in <module>
    import smash_watcher
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_watcher.py", line 15, in <module>
    print(test)
NameError: name 'test' is not defined

[2019-05-08 23:30:31]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 352, in <module>
    print(test)
NameError: name 'test' is not defined

