[2019-04-25 21:53:55]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 96, in <module>
    watcher = smash_watcher.Watcher()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_watcher.py", line 34, in __init__
    self.sim_list = [0] * list_limit
NameError: name 'list_limit' is not defined

[2019-04-25 21:51:35]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 95, in <module>
    watcher = Watcher()
NameError: name 'Watcher' is not defined

[2019-04-25 21:51:05]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 90, in <module>
    gui_queue = Queue()
NameError: name 'Queue' is not defined

[2019-04-25 17:30:23]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 159, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 144, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 153, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 95, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 166, in read_cards
    id_slice = screen.crop(ut.COORDS['LOBBY']['EXACT']['CARDS_SLICE_ID'])
KeyError: 'CARDS_SLICE_ID'

[2019-04-25 17:30:03]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 159, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 144, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 153, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 95, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 167, in read_cards
    color_slice = screen.crop(ut.COORDS['LOBBY']['EXACT']['CARDS_SLICE_COLOR'])
KeyError: 'CARDS_SLICE_COLOR'

[2019-04-25 17:25:20]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 159, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 145, in fight_tester
    game.read_start_screen(fight_start_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 200, in read_start_screen
    self.get_stock_templates(screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 210, in get_stock_templates
    for i, edge in enumerate(ut.COORDS['IN_GAME']['RELATIVE']['PLAYER_INFO'][self.player_count]):
KeyError: 0

[2019-04-25 17:14:17]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 159, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 144, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 153, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 190, in read_cards
    if len(teams) == 2 and self.player_count > 2:
NameError: name 'teams' is not defined

[2019-04-25 17:08:41]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 159, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 147, in fight_tester
    game.read_results_screen(fight_results_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 236, in read_results_screen
    print(self.teams[color])
TypeError: list indices must be integers or slices, not str

[2019-04-25 17:08:33]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 159, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 147, in fight_tester
    game.read_results_screen(fight_results_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 236, in read_results_screen
    print(self.team[color])
AttributeError: 'Game' object has no attribute 'team'

[2019-04-25 16:59:37]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 159, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 150, in fight_tester
    json.dump(game.serialize(), outfile, separators=(',',':'))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:44:24]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.teams[0].players[0].serialize()))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

[2019-04-25 16:44:05]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.teams[0].players[0].serialize()))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

[2019-04-25 16:43:44]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.teams[0].players[0].serialize()))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

[2019-04-25 16:35:54]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.teams[0].players[0].serialize()))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

[2019-04-25 16:35:19]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.teams[0].players[0].serialize()))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 40, in serialize
    img_str = self.player_name_image.tostring()
AttributeError: 'list' object has no attribute 'tostring'

[2019-04-25 16:34:47]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.teams[0].players[0].serialize()))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 39, in serialize
    img_str = self.player_name_image.tostring()
AttributeError: 'list' object has no attribute 'tostring'

[2019-04-25 16:30:35]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.teams[0].players[0].serialize()))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:30:24]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.teams[0].serialize()))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:29:59]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 158, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    print(json.dumps(game.serialize()))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:29:42]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(json.dumps(game.serialize()))
NameError: name 'json' is not defined

[2019-04-25 16:25:39]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in __str__
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in <listcomp>
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in __str__
    return json.dumps(_copy.__dict__)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:23:44]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 119, in __str__
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 119, in <listcomp>
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 42, in __str__
    return json.dumps(_copy.__dict__)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:21:59]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in __str__
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in <listcomp>
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 39, in __str__
    img_str = json.dumps(self.player_name_image.tolist())
AttributeError: 'list' object has no attribute 'tolist'

[2019-04-25 16:20:20]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in __str__
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in <listcomp>
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 42, in __str__
    return json.dumps(_copy.__dict__)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:18:05]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in __str__
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in <listcomp>
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 42, in __str__
    return json.dumps(_copy.__dict__)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:17:43]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in __str__
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in <listcomp>
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 42, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Player is not JSON serializable

[2019-04-25 16:16:44]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in __str__
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in <listcomp>
    players = [json.loads(str(player)) for player in self.players]
TypeError: __str__ returned non-string (type Player)

[2019-04-25 16:16:06]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in __str__
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 120, in <listcomp>
    players = [json.loads(str(player)) for player in self.players]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 39, in __str__
    img_str = json.dumps(self.player_name_image_array)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:15:24]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 124, in __str__
    return json.dumps(_copy.__dict__)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

[2019-04-25 16:14:06]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 124, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 16:11:41]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 124, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 16:05:49]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 116, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 16:05:27]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 16:05:12]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 16:01:58]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 16:01:14]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 157, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 148, in fight_tester
    print(str(game.teams[0]))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 16:00:18]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 156, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 147, in fight_tester
    print(str(game))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 135, in __str__
    teams = [json.loads(str(team)) for team in self.teams]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 135, in <listcomp>
    teams = [json.loads(str(team)) for team in self.teams]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 15:58:54]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 156, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 147, in fight_tester
    print(str(game))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 135, in __str__
    teams = [json.loads(str(team)) for team in self.teams]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 135, in <listcomp>
    teams = [json.loads(str(team)) for team in self.teams]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in __str__
    return json.dumps(_copy)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Team is not JSON serializable

[2019-04-25 15:53:05]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 156, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 147, in fight_tester
    print(repr(game))
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 135, in __repr__
    teams = [repr(team) for team in self.teams]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 135, in <listcomp>
    teams = [repr(team) for team in self.teams]
TypeError: __repr__ returned non-string (type Team)

[2019-04-25 15:50:30]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 144, in fight_tester
    game.read_start_screen(fight_start_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 185, in read_start_screen
    self.get_stock_templates(screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 195, in get_stock_templates
    for i, edge in enumerate(ut.COORDS['IN_GAME']['RELATIVE']['PLAYER_INFO'][len(self.players)]):
AttributeError: 'Game' object has no attribute 'players'

[2019-04-25 15:50:09]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 141, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 168, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 40, in read_card
    self.check_color(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 49, in check_color
    pixel = card.crop(COORDS['LOBBY']['RELATIVE']['COLOR'])
NameError: name 'COORDS' is not defined

[2019-04-25 15:49:01]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 141, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 165, in read_cards
    color = ut.match_color(arr=pixels[i - 5], mode='CARDS')[0]
TypeError: 'NoneType' object is not subscriptable

[2019-04-25 15:48:10]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 141, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 165, in read_cards
    color = ut.match_color(arr=pixels[i - 5], mode='CARDS')[0]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 246, in match_color
    elif arr:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

[2019-04-25 15:39:39]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 141, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 165, in read_cards
    color = ut.match_color(pixels[i - 5], 'CARDS')[0]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 244, in match_color
    sample = [rgb for row in np.asarray(pixel) for rgb in row][0]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 244, in <listcomp>
    sample = [rgb for row in np.asarray(pixel) for rgb in row][0]
TypeError: 'numpy.uint8' object is not iterable

[2019-04-25 15:38:58]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 141, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 165, in read_cards
    color = ut.match_color(pixels[i - 5])[0]
TypeError: match_color() missing 1 required positional argument: 'mode'

[2019-04-25 13:46:17]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 138, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 165, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 44, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 75, in get_character_name
    templates = TEMPLATES['UNRECOGNIZED']
NameError: name 'TEMPLATES' is not defined

[2019-04-25 13:41:03]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 139, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 166, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 44, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 79, in get_character_name
    ut.TEMPLATES['UNRECOGNIZED'] += 1
TypeError: unsupported operand type(s) for +=: 'dict' and 'int'

[2019-04-25 13:38:46]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 139, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 166, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 44, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 84, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 77, in get_character_name
    ut.BASE_DIR, 'templates', 'unrecognized', ut.TEMPLATES['UNRECOGNIZED'] + '.png'
TypeError: unsupported operand type(s) for +: 'int' and 'str'

[2019-04-25 13:32:46]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 139, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 166, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 44, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 86, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 77, in get_character_name
    ut.BASE_DIR, 'templates', 'unrecognized', ut.TEMPLATES['UNRECOGNIZED'] + '.png'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

[2019-04-25 13:24:44]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 139, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 166, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 44, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 85, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 77, in get_character_name
    ut.BASE_DIR, 'templates', 'unrecognized', ut.TEMPLATES['UNRECOGNIZED'] + '.png'
TypeError: unsupported operand type(s) for +: 'dict' and 'str'

[2019-04-25 13:14:31]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 136, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 163, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 44, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 77, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 76, in get_character_name
    filepath = os.path.join(BASE_DIR, 'templates', name_as_read + '.png')
NameError: name 'BASE_DIR' is not defined

[2019-04-25 13:12:47]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 146, in fight_tester
    game.read_results_screen(fight_results_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 216, in read_results_screen
    sim_template = find_most_similar(crop, templates)
NameError: name 'find_most_similar' is not defined

[2019-04-25 12:45:01]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 134, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 161, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 45, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 92, in read_number
    num = int(os.path.splitext(template_name)[0].split('P')[1])
NameError: name 'os' is not defined

[2019-04-25 12:44:14]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 134, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 161, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 58, in get_character_name
    crop = card.crop(COORDS['LOBBY']['RELATIVE']['CHARACTER_NAME'])
NameError: name 'COORDS' is not defined

[2019-04-25 12:43:12]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 155, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 143, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 133, in read_card_screen
    self.read_basic_info(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 76, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 139, in read_basic_info
    crop = screen.crop(COORDS['LOBBY']['EXACT']['GAME_INFO'])
NameError: name 'COORDS' is not defined

[2019-04-25 12:35:44]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 160, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    game.read_start_screen(fight_start_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 76, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 178, in read_start_screen
    type(self.mode)
TypeError: 'str' object is not callable

[2019-04-25 12:34:27]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 160, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in fight_tester
    game.read_start_screen(fight_start_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 76, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 178, in read_start_screen
    print(type(self.mode))
TypeError: 'str' object is not callable

[2019-04-25 12:29:37]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 156, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 141, in fight_tester
    fight_results_screen = Image.open(os.path.join(CAPTURES_DIR, n + '.5.FIGHT_RESULTS.png'))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cunss\\OneDrive\\Documents\\Projects\\smash\\reader\\smash_reader\\captures\\0001.5.FIGHT_RESULTS.png'

[2019-04-25 11:46:15]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 156, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 141, in fight_tester
    fight_results_screen = Image.open(os.path.join(CAPTURES_DIR, n + '.5.FIGHT_RESULTS.png'))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cunss\\OneDrive\\Documents\\Projects\\smash\\reader\\smash_reader\\captures\\0001.5.FIGHT_RESULTS.png'

[2019-04-25 11:44:51]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 156, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    fight_end_screen = Image.open(os.path.join(CAPTURES_DIR, n + '4.FIGHT_END.png'))
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cunss\\OneDrive\\Documents\\Projects\\smash\\reader\\smash_reader\\captures\\00014.FIGHT_END.png'

[2019-04-23 21:15:59]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 141, in read_cards
    crop.show()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2051, in show
    _show(self, title=title, command=command)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2924, in _show
    _showxv(image, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2929, in _showxv
    ImageShow.show(image, title, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 53, in show
    if viewer.show(image, title=title, **options):
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 77, in show
    return self.show_image(image, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 97, in show_image
    return self.show_file(self.save_image(image), **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 101, in show_file
    os.system(self.get_command(file, **options))
KeyboardInterrupt

[2019-04-23 21:15:00]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 141, in read_cards
    crop.show()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2051, in show
    _show(self, title=title, command=command)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2924, in _show
    _showxv(image, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2929, in _showxv
    ImageShow.show(image, title, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 53, in show
    if viewer.show(image, title=title, **options):
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 77, in show
    return self.show_image(image, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 97, in show_image
    return self.show_file(self.save_image(image), **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 101, in show_file
    os.system(self.get_command(file, **options))
KeyboardInterrupt

[2019-04-23 21:14:24]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 68, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 76, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 76, in get_character_name
    pil.show()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2051, in show
    _show(self, title=title, command=command)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2924, in _show
    _showxv(image, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2929, in _showxv
    ImageShow.show(image, title, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 53, in show
    if viewer.show(image, title=title, **options):
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 77, in show
    return self.show_image(image, **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 97, in show_image
    return self.show_file(self.save_image(image), **options)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageShow.py", line 101, in show_file
    os.system(self.get_command(file, **options))
KeyboardInterrupt

[2019-04-23 20:35:40]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 46, in read_card
    self.read_gsp(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 76, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 99, in read_gsp
    text = read_image(crop, 'gsp')
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 145, in read_image
    text = pytesseract.image_to_string(image, config=configs[config_type])
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 188, in run_tesseract
    status_code, error_string = proc.wait(), proc.stderr.read()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1230, in _wait
    timeout_millis)
KeyboardInterrupt

[2019-04-23 20:34:17]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 76, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    if name.upper() not in TEMPLATES['CHARACTER_NAMES']:
KeyError: 'CHARACTER_NAMES'

[2019-04-23 20:34:09]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 75, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    if name.upper() not in TEMPLATES['CHARACTER_NAMES']:
KeyError: 'CHARACTER_NAMES'

[2019-04-23 20:33:57]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    if name.upper() not in TEMPLATES['CHARACTER_NAMES']:
KeyError: 'CHARACTER_NAMES'

[2019-04-23 20:33:43]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    if name.upper() not in TEMPLATES['CHARACTER_NAMES']:
KeyError: 'CHARACTER_NAMES'

[2019-04-23 20:30:38]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    if name.upper() not in TEMPLATES['CHARACTER_NAMES']:
KeyError: 'CHARACTER_NAMES'

[2019-04-23 20:23:38]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    if name.upper() not in TEMPLATES['CHARACTER_NAMES']:
KeyError: 'CHARACTER_NAMES'

[2019-04-23 20:21:55]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in get_character_name
    if name.upper() not in TEMPLATES['CHARACTER_NAMES']:
KeyError: 'CHARACTER_NAMES'

[2019-04-23 20:15:12]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 117, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 144, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 46, in read_card
    self.read_gsp(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 99, in read_gsp
    text = read_image(crop, 'gsp')
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 141, in read_image
    text = pytesseract.image_to_string(image, config=configs[config_type])
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 188, in run_tesseract
    status_code, error_string = proc.wait(), proc.stderr.read()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1230, in _wait
    timeout_millis)
KeyboardInterrupt

[2019-04-23 20:11:16]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 116, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 143, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 60, in get_character_name
    template_name, sim = find_most_similar(pil, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 208, in compare_skim
    sim, diff = compare_ssim(sample, template, full=True, multichannel=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 102, in compare_ssim
    ch_result = compare_ssim(X[..., ch], Y[..., ch], **args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 182, in compare_ssim
    ux = filter_func(X, **filter_args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 843, in uniform_filter
    cval, origin)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 782, in uniform_filter1d
    mode = _ni_support._extend_mode_to_code(mode)
KeyboardInterrupt

[2019-04-23 20:03:16]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 68, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 116, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 143, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 75, in get_character_name
    pil.save(filepath)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2004, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: 'C:\\. wendy.png'

[2019-04-23 20:01:01]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 142, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 45, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 86, in read_number
    template_name, sim = find_most_similar(crop, TEMPLATES['PLAYER_NUMBERS'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 208, in compare_skim
    sim, diff = compare_ssim(sample, template, full=True, multichannel=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 102, in compare_ssim
    ch_result = compare_ssim(X[..., ch], Y[..., ch], **args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 183, in compare_ssim
    uy = filter_func(Y, **filter_args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 833, in uniform_filter
    output = _ni_support._get_output(output, input)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\_ni_support.py", line 75, in _get_output
    output = numpy.zeros(shape, dtype=input.dtype.name)
KeyboardInterrupt

[2019-04-23 20:00:00]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 143, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 60, in get_character_name
    template_name, sim = find_most_similar(pil, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 208, in compare_skim
    sim, diff = compare_ssim(sample, template, full=True, multichannel=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 102, in compare_ssim
    ch_result = compare_ssim(X[..., ch], Y[..., ch], **args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 182, in compare_ssim
    ux = filter_func(X, **filter_args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 843, in uniform_filter
    cval, origin)
KeyboardInterrupt

[2019-04-23 19:53:46]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 143, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 60, in get_character_name
    template_name, sim = find_most_similar(pil, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 208, in compare_skim
    sim, diff = compare_ssim(sample, template, full=True, multichannel=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 102, in compare_ssim
    ch_result = compare_ssim(X[..., ch], Y[..., ch], **args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 182, in compare_ssim
    ux = filter_func(X, **filter_args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 837, in uniform_filter
    axes = list(range(input.ndim))
KeyboardInterrupt

[2019-04-23 19:50:02]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 142, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 60, in get_character_name
    template_name, sim = find_most_similar(pil, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 208, in compare_skim
    sim, diff = compare_ssim(sample, template, full=True, multichannel=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 102, in compare_ssim
    ch_result = compare_ssim(X[..., ch], Y[..., ch], **args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 182, in compare_ssim
    ux = filter_func(X, **filter_args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 833, in uniform_filter
    output = _ni_support._get_output(output, input)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\_ni_support.py", line 75, in _get_output
    output = numpy.zeros(shape, dtype=input.dtype.name)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\_dtype.py", line 334, in _name_get
    if np.issubdtype(dtype, np.flexible) and not _isunsized(dtype):
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\numerictypes.py", line 392, in issubdtype
    if not issubclass_(arg1, generic):
KeyboardInterrupt

[2019-04-23 19:49:25]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 152, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 141, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 142, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 60, in get_character_name
    template_name, sim = find_most_similar(pil, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 208, in compare_skim
    sim, diff = compare_ssim(sample, template, full=True, multichannel=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 102, in compare_ssim
    ch_result = compare_ssim(X[..., ch], Y[..., ch], **args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 182, in compare_ssim
    ux = filter_func(X, **filter_args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 843, in uniform_filter
    cval, origin)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 784, in uniform_filter1d
    origin)
KeyboardInterrupt

[2019-04-23 19:48:50]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 115, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 142, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 46, in read_card
    self.read_gsp(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 97, in read_gsp
    text = read_image(crop, 'gsp')
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 141, in read_image
    text = pytesseract.image_to_string(image, config=configs[config_type])
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 188, in run_tesseract
    status_code, error_string = proc.wait(), proc.stderr.read()
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1230, in _wait
    timeout_millis)
KeyboardInterrupt

[2019-04-23 19:47:50]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 114, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 141, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 60, in get_character_name
    template_name, sim = find_most_similar(pil, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 215, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 208, in compare_skim
    sim, diff = compare_ssim(sample, template, full=True, multichannel=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 102, in compare_ssim
    ch_result = compare_ssim(X[..., ch], Y[..., ch], **args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 188, in compare_ssim
    uxy = filter_func(X * Y, **filter_args)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 843, in uniform_filter
    cval, origin)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\filters.py", line 779, in uniform_filter1d
    output = _ni_support._get_output(output, input)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\ndimage\_ni_support.py", line 76, in _get_output
    elif type(output) in [type(type), type(numpy.zeros((4,)).dtype)]:
KeyboardInterrupt

[2019-04-23 19:45:33]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 140, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 111, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 138, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 67, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

[2019-04-23 19:44:38]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 151, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    card_screen = Image.open(os.path.join(CAPTURES_DIR, n + '.2.LOBBY_CARDS.png'))
NameError: name 'n' is not defined

[2019-04-23 19:38:48]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 111, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 138, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 67, in get_character_name
    name = difflib.get_close_matches(name_as_read, CHARACTER_NAMES, n=1)[0]
IndexError: list index out of range

[2019-04-23 19:35:38]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 111, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 138, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 70, in get_character_name
    self.character_name = name
UnboundLocalError: local variable 'name' referenced before assignment

[2019-04-23 19:34:09]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 111, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 138, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 60, in get_character_name
    template_name, sim = find_most_similar(pil, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 212, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 212, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 198, in compare_skim
    sample = cv2.cvtColor(np.array(sample), cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<1,-1,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1


[2019-04-23 19:29:33]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 110, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 137, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 45, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 86, in read_number
    self.number = i + 1
NameError: name 'i' is not defined

[2019-04-23 19:28:42]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 110, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 137, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 59, in get_character_name
    template_name, sim = find_most_similar(crop, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 163, in find_most_similar
    sim = avg_sim(sample, templates[template_name])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 212, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 212, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 176, in compare_chops
    copy2, arr2 = convert_to_bw(copy2)
ValueError: too many values to unpack (expected 2)

[2019-04-23 19:28:26]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 110, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 137, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 43, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 59, in get_character_name
    template_name, sim = find_most_similar(crop, TEMPLATES['CHARACTER_NAMES'])
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 162, in find_most_similar
    for template_name in template:
NameError: name 'template' is not defined

[2019-04-23 18:29:37]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 104, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 131, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 45, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 80, in read_number
    self.number = i + 1
TypeError: can only concatenate list (not "int") to list

[2019-04-23 18:28:39]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 104, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 131, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 45, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 76, in read_number
    i = find_most_similar(crop, templates)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 160, in find_most_similar
    sim = compare_skim(sample, template)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 202, in compare_skim
    sim, diff = compare_ssim(sample, template, full=True, multichannel=True)
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\measure\_structural_similarity.py", line 83, in compare_ssim
    if not X.shape == Y.shape:
AttributeError: 'PngImageFile' object has no attribute 'shape'

[2019-04-23 18:25:43]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 104, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 131, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 45, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 76, in read_number
    i = find_most_similar(crop, templates)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 160, in find_most_similar
    sim = compare_skim(sample, template)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 196, in compare_skim
    template = cv2.cvtColor(np.array(template), cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<1,-1,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1


[2019-04-23 18:25:34]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 104, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 131, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 45, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 76, in read_number
    i = find_most_similar(crop, templates)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 160, in find_most_similar
    sim = compare_chops(sample, template)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 173, in compare_chops
    copy2, arr2 = convert_to_bw(copy2)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 147, in convert_to_bw
    img_gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<1,-1,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1


[2019-04-23 18:24:58]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 149, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 138, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 104, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 131, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 45, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 72, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 76, in read_number
    i = find_most_similar(crop, templates)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 160, in find_most_similar
    sim = avg_sim(sample, template)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 205, in avg_sim
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 205, in <listcomp>
    sims = [comp_func(sample, template) for comp_func in comp_funcs]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 173, in compare_chops
    copy2, arr2 = convert_to_bw(copy2)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 147, in convert_to_bw
    img_gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<1,-1,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1


[2019-04-22 19:33:30]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 177, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 166, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 121, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 147, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 71, in read_card
    self.read_number(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 97, in read_number
    num = read_image(pil, 'player_number')[-1]
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 93, in read_image
    text = pytesseract.image_to_string(image, config=configs[config_type])
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 184, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
KeyboardInterrupt

[2019-04-22 19:33:22]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 177, in <module>
    fight_tester()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 166, in fight_tester
    game.read_card_screen(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 121, in read_card_screen
    self.read_cards(card_screen)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 147, in read_cards
    player.read_card(crop)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 69, in read_card
    self.get_character_name(card)
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_game.py", line 84, in get_character_name
    name_as_read = read_image(pil).lower()
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash_utility.py", line 93, in read_image
    text = pytesseract.image_to_string(image, config=configs[config_type])
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 188, in run_tesseract
    status_code, error_string = proc.wait(), proc.stderr.read()
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\Eh\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1230, in _wait
    timeout_millis)
KeyboardInterrupt

[2019-04-22 19:15:23]
Traceback (most recent call last):
  File "C:\Users\cunss\OneDrive\Documents\Projects\smash\reader\smash_reader\smash.py", line 177, in <module>
    print(test)
NameError: name 'test' is not defined

